blog/urls.py
from django.urls import path
from . import views
# from .views import post_detail  # Importez votre vue post_detail

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<slug:slug>/', views.post_detail, name='post_detail'),
]

    # path('sitemap.xml', views.sitemap, name='sitemap'),
    # path('robots.txt', views.robots, name='robots'),
    # path('googlee3c7e3b2e1f5c0d8.html', views.google, name='google'),
    # path('BingSiteAuth.xml', views.bing, name='bing'),
    # path('Yandex_9b5d0a3c4c6a5d1d.html', views.yandex, name='yandex'),
    # path('sitemap.xml.gz', views.sitemap_gz, name='sitemap_gz'),
    # path('sitemap.xml.gz.txt', views.sitemap_gz_txt, name='sitemap_gz_txt'),
    # path('sitemap.xml.txt', views.sitemap_txt, name='sitemap_txt'),
    # path('sitemap.xml.zip', views.sitemap_zip, name='sitemap_zip'),
    # path('sitemap.xml.zip.txt', views.sitemap_zip_txt, name='sitemap_zip_txt'),
    # path('sitemap.xml.xz', views.sitemap_xz, name='sitemap_xz'),
    # path('sitemap.xml.xz.txt', views.sitemap_xz_txt, name='sitemap_xz_txt'),
    # path('sitemap.xml.bz2', views.sitemap_bz2, name='sitemap_bz2'),
    # path('sitemap.xml.bz2.txt', views.sitemap_bz2_txt, name='sitemap_bz2_txt'),
    # path('sitemap.xml.br', views.sitemap_br, name='sitemap_br'),

silenus/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('post/', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)
    description = models.CharField(max_length=100)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(choices=STATUS_CHOICES, default='draft', max_length=10)
    published = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posted_by')


    def __str__(self) -> str:
        return self.title

        

cv/models.py
from django.db import models

# Create your models here.

quiz/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import Post

# Create your views here.
def post_list(request):
    object_list = Post.objects.all()
    paginator = Paginator(object_list, 1) # 2 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    context = {
        'posts': posts,
        'page': page,
    }    
    return render(request, 'blog/post/list.html', {'posts': posts})

def post_detail(request, slug):
    post = Post.objects.get(slug=slug)
    # post = get_object_or_404(Post, slug=slug)
    return render(request, 'blog/post/detail.html', {'post': post}) 

    # try:
    #     post = Post.objects.get(slug=slug)
    # except Post.DoesNotExist:
    #     raise Http404("Post does not exist")
    # return render(request, 'blog/post/detail.html', {'post': post})

cv/views.py
from django.shortcuts import render

# Create your views here.

quiz/views.py
from django.shortcuts import render

# Create your views here.

blog/templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>My Web Page</title>
    {% comment %} cdn for bootstrap {% endcomment %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    {% block content %}
    {% endblock %}
    {% comment %} cdn for bootstrap {% endcomment %}    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

blog/templates/blog/layout/pagination.html
<nav aria-label="...">
    <ul class="pagination">
        {% if posts.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ posts.previous_page_number }}" tabindex="-1">Previous</a>
            </li>
        {% endif %}
        {% for i in posts.paginator.page_range %}
            <li class="page-item {% if posts.number == i %}active{% endif %}">
                <a class="page-link" href="?page={{ i }}">{{ i }}{% if posts.number == i %}<span class="sr-only">(current)</span>{% endif %}</a>
            </li>
        {% endfor %}
        {% if posts.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ posts.next_page_number }}">Next</a>
            </li>
        {% endif %}
    </ul>
</nav>
<nav aria-label="...">
    <ul class="pagination">
        {% if posts.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ posts.previous_page_number }}">Previous</a>
            </li>
        {% endif %}
        <li class="page-item">
            <a class="page-link" href="#">{{ posts.number }} sur {{ posts.paginator.num_pages }}</a>
        </li>
        {% if posts.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ posts.next_page_number }}">Next</a>
            </li>
        {% endif %}
    </ul>
</nav>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p>{{ post.created }}</p>
    <hr>
    <p>{{ post.body }}</p>
{% endblock %}    

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% block content %}
    <h1>Liste des publications</h1>
    {% for post in posts %}
        {% comment %} <a href="/post/{{ post.slug }}/"><h2>{{ post.title }}</h2></a> {% endcomment %}
        <a href="{% url 'blog:post_detail' post.slug %}"><h2>{{ post.title }}</h2></a>
        <p>{{ post.created }}</p>
        <p>{{ post.body }}</p>
    {% endfor %}
    {% comment %} include "blog/pagination.html" {% endcomment %}
    {% include "blog/layout/pagination.html" %}
{% endblock %}


    